# Generated by Django 2.2.6 on 2020-04-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_auto_20200401_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='comparte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 1'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 2'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 3'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 4'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 5'),
        ),
    ]
