# Generated by Django 2.2.6 on 2020-04-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_auto_20200402_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='Author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='idiomas',
            field=models.CharField(blank=True, choices=[('Español Latino', 'Español Latino'), ('Español Castellano', 'Español Castellano'), ('Español Subtitulado', 'Español Subtitulado'), ('Ingles', 'Ingles')], default=('Español Latino', 'Español Latino'), max_length=150, null=True),
        ),
    ]
