# Generated by Django 2.2.6 on 2020-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_auto_20200403_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesps2',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 1'),
        ),
        migrations.AlterField(
            model_name='gamesps2',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 2'),
        ),
        migrations.AlterField(
            model_name='gamesps2',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 3'),
        ),
        migrations.AlterField(
            model_name='gamesps2',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 4'),
        ),
        migrations.AlterField(
            model_name='gamesps2',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 5'),
        ),
        migrations.AlterField(
            model_name='gamesps3',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 1'),
        ),
        migrations.AlterField(
            model_name='gamesps3',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 2'),
        ),
        migrations.AlterField(
            model_name='gamesps3',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 3'),
        ),
        migrations.AlterField(
            model_name='gamesps3',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 4'),
        ),
        migrations.AlterField(
            model_name='gamesps3',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 5'),
        ),
        migrations.AlterField(
            model_name='gamespsx',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 1'),
        ),
        migrations.AlterField(
            model_name='gamespsx',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 2'),
        ),
        migrations.AlterField(
            model_name='gamespsx',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 3'),
        ),
        migrations.AlterField(
            model_name='gamespsx',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 4'),
        ),
        migrations.AlterField(
            model_name='gamespsx',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 5'),
        ),
    ]
