# Generated by Django 2.2.6 on 2020-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_auto_20200424_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='anio',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
