# Generated by Django 2.2.6 on 2020-05-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0011_auto_20200425_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='peliculas',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='anio',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre:')),
                ('nombre_original', models.CharField(max_length=250, verbose_name='Nombre Original:')),
                ('slug_serie', models.SlugField(blank=True, max_length=250, null=True)),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion:')),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('Author', models.CharField(max_length=150)),
                ('calificacion', models.CharField(max_length=100)),
                ('descargas', models.IntegerField()),
                ('idiomas', models.CharField(blank=True, choices=[('Español Latino', 'Español Latino'), ('Español Castellano', 'Español Castellano'), ('Español Subtitulado', 'Español Subtitulado'), ('Ingles', 'Ingles')], default=('Español Latino', 'Español Latino'), max_length=150, null=True)),
                ('fecha_estreno', models.DateField(verbose_name='Fecha de Estreno')),
                ('fecha_subida', models.DateField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('anio', models.CharField(blank=True, max_length=4, null=True)),
                ('trailer', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('Emision', 'Emision'), ('Finalizado', 'Finalizado'), ('Temporada Final', 'Temporada Final')], default=('Emision', 'Emision'), max_length=150, null=True, verbose_name='Estado:')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('reparto', models.CharField(max_length=1000, verbose_name='Reparto')),
                ('online', models.CharField(max_length=500, verbose_name='Link Online')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 4')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 5')),
                ('enlacegd', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive')),
                ('comparte', models.CharField(blank=True, max_length=500, null=True)),
                ('enlace_publi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad')),
                ('genero', models.ManyToManyField(to='contenido.categorias', verbose_name='Genero Juego:')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
