# Generated by Django 2.2.6 on 2020-05-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0013_temporadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporadas',
            name='ntemporada',
            field=models.CharField(choices=[('Primera', 'Primera'), ('Segunda', 'Segunda'), ('Tercera', 'Tercera'), ('Cuarta', 'Cuarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Septima', 'Septima'), ('Octava', 'Octava'), ('Novena', 'Novena'), ('Decima', 'Decima'), ('Once', 'Once'), ('Doce', 'Doce'), ('Trece', 'Trece'), ('Catorce', 'Catorce'), ('Quince', 'Quince'), ('Dieciséis', 'Dieciséis'), ('Diecisiete', 'Diecisiete'), ('Dieciocho', 'Dieciocho'), ('Diecinueve', 'Diecinueve'), ('Veinte', 'Veinte')], default=('Primera', 'Primera'), max_length=150),
        ),
    ]
