# Generated by Django 2.2.6 on 2020-05-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_temporadas_ntemporada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ntemporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug_ntemporada', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='temporadas',
            name='ntemporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.ntemporada'),
        ),
    ]
