# Generated by Django 2.2.6 on 2020-05-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0015_auto_20200505_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='enlace_publi',
        ),
        migrations.RemoveField(
            model_name='series',
            name='enlacegd',
        ),
        migrations.RemoveField(
            model_name='series',
            name='online',
        ),
        migrations.RemoveField(
            model_name='temporadas',
            name='enlace_publi',
        ),
        migrations.RemoveField(
            model_name='temporadas',
            name='enlacegd',
        ),
        migrations.RemoveField(
            model_name='temporadas',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='temporadas',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='temporadas',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='temporadas',
            name='region',
        ),
    ]
