# Generated by Django 2.2.6 on 2020-05-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0018_auto_20200506_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ncapitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug_capitulos', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='capitulos',
            name='temporada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.temporadas'),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='ncapitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.ncapitulos'),
            preserve_default=False,
        ),
    ]
