# Generated by Django 2.2.6 on 2020-05-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0019_auto_20200507_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='ncapitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.ncapitulos'),
        ),
    ]
