# Generated by Django 2.2.6 on 2020-05-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0021_auto_20200512_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamespc',
            name='enlacemg',
        ),
        migrations.RemoveField(
            model_name='gamespc',
            name='enlacemg2',
        ),
        migrations.RemoveField(
            model_name='gamespc',
            name='enlacemg3',
        ),
        migrations.RemoveField(
            model_name='gamespc',
            name='enlacemg4',
        ),
        migrations.RemoveField(
            model_name='gamespc',
            name='enlacemg5',
        ),
        migrations.RemoveField(
            model_name='gamespc',
            name='region',
        ),
        migrations.RemoveField(
            model_name='gamesps2',
            name='enlacemg',
        ),
        migrations.RemoveField(
            model_name='gamesps2',
            name='enlacemg2',
        ),
        migrations.RemoveField(
            model_name='gamesps2',
            name='enlacemg3',
        ),
        migrations.RemoveField(
            model_name='gamesps2',
            name='enlacemg4',
        ),
        migrations.RemoveField(
            model_name='gamesps2',
            name='enlacemg5',
        ),
        migrations.RemoveField(
            model_name='gamesps3',
            name='enlacemg',
        ),
        migrations.RemoveField(
            model_name='gamesps3',
            name='enlacemg2',
        ),
        migrations.RemoveField(
            model_name='gamesps3',
            name='enlacemg3',
        ),
        migrations.RemoveField(
            model_name='gamesps3',
            name='enlacemg4',
        ),
        migrations.RemoveField(
            model_name='gamesps3',
            name='enlacemg5',
        ),
        migrations.RemoveField(
            model_name='gamesps3',
            name='region',
        ),
        migrations.RemoveField(
            model_name='gamespsx',
            name='enlacemg',
        ),
        migrations.RemoveField(
            model_name='gamespsx',
            name='enlacemg2',
        ),
        migrations.RemoveField(
            model_name='gamespsx',
            name='enlacemg3',
        ),
        migrations.RemoveField(
            model_name='gamespsx',
            name='enlacemg4',
        ),
        migrations.RemoveField(
            model_name='gamespsx',
            name='enlacemg5',
        ),
        migrations.RemoveField(
            model_name='gamespsx',
            name='region',
        ),
        migrations.AddField(
            model_name='gamespc',
            name='enlace_publi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad'),
        ),
        migrations.AddField(
            model_name='gamespc',
            name='enlacegd10',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 10'),
        ),
        migrations.AddField(
            model_name='gamespc',
            name='enlacegd6',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 6'),
        ),
        migrations.AddField(
            model_name='gamespc',
            name='enlacegd7',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 7'),
        ),
        migrations.AddField(
            model_name='gamespc',
            name='enlacegd8',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 8'),
        ),
        migrations.AddField(
            model_name='gamespc',
            name='enlacegd9',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 9'),
        ),
        migrations.AddField(
            model_name='gamesps2',
            name='enlace_publi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad'),
        ),
        migrations.AddField(
            model_name='gamesps2',
            name='enlacegd10',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 10'),
        ),
        migrations.AddField(
            model_name='gamesps2',
            name='enlacegd6',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 6'),
        ),
        migrations.AddField(
            model_name='gamesps2',
            name='enlacegd7',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 7'),
        ),
        migrations.AddField(
            model_name='gamesps2',
            name='enlacegd8',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 8'),
        ),
        migrations.AddField(
            model_name='gamesps2',
            name='enlacegd9',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 9'),
        ),
        migrations.AddField(
            model_name='gamesps3',
            name='enlace_publi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad'),
        ),
        migrations.AddField(
            model_name='gamesps3',
            name='enlacegd10',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 10'),
        ),
        migrations.AddField(
            model_name='gamesps3',
            name='enlacegd6',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 6'),
        ),
        migrations.AddField(
            model_name='gamesps3',
            name='enlacegd7',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 7'),
        ),
        migrations.AddField(
            model_name='gamesps3',
            name='enlacegd8',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 8'),
        ),
        migrations.AddField(
            model_name='gamesps3',
            name='enlacegd9',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 9'),
        ),
        migrations.AddField(
            model_name='gamespsx',
            name='enlace_publi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad'),
        ),
        migrations.AddField(
            model_name='gamespsx',
            name='enlacegd10',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 10'),
        ),
        migrations.AddField(
            model_name='gamespsx',
            name='enlacegd6',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 6'),
        ),
        migrations.AddField(
            model_name='gamespsx',
            name='enlacegd7',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 7'),
        ),
        migrations.AddField(
            model_name='gamespsx',
            name='enlacegd8',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 8'),
        ),
        migrations.AddField(
            model_name='gamespsx',
            name='enlacegd9',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 9'),
        ),
        migrations.AlterField(
            model_name='gamespc',
            name='comparte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gamespc',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AlterField(
            model_name='gamesps2',
            name='comparte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gamesps2',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AlterField(
            model_name='gamesps3',
            name='comparte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gamesps3',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AlterField(
            model_name='gamespsx',
            name='comparte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gamespsx',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
    ]
