# Generated by Django 2.2.6 on 2020-05-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0020_auto_20200508_1442'),
        ('contenido', '0022_auto_20200514_2222'),
    ]

    operations = [
    ]
