# Generated by Django 2.2.6 on 2020-05-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias_cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug_categoria_cur', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='lenguaje_cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug_categoria_len', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='plataforma_cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug_categoria_pla', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre:')),
                ('nombre_original', models.CharField(max_length=250, verbose_name='Nombre Original:')),
                ('slug_curso', models.SlugField(blank=True, max_length=250, null=True)),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion:')),
                ('Author', models.CharField(max_length=150)),
                ('calificacion', models.CharField(max_length=100)),
                ('descargas', models.IntegerField()),
                ('idiomas', models.CharField(blank=True, choices=[('Español Latino', 'Español Latino'), ('Español Castellano', 'Español Castellano'), ('Español Subtitulado', 'Español Subtitulado'), ('Ingles', 'Ingles')], default=('Español Latino', 'Español Latino'), max_length=150, null=True)),
                ('fecha_estreno', models.DateField(verbose_name='Fecha del Curso')),
                ('fecha_subida', models.DateField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('anio', models.CharField(blank=True, max_length=4, null=True)),
                ('trailer', models.CharField(max_length=100)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 4')),
                ('enlacegd', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive')),
                ('enlacegd2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive 2')),
                ('enlacegd3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive 3')),
                ('enlacegd4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive 4')),
                ('enlacegd5', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive 5')),
                ('enlacesub', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Subtitulo')),
                ('enlacemg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Mega ')),
                ('enlacemg2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Mega 2')),
                ('enlacemg3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Mega 3')),
                ('enlacemg4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Mega 4')),
                ('enlacemg5', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Mega 5')),
                ('comparte', models.CharField(blank=True, max_length=500, null=True)),
                ('enlace_publi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad')),
                ('enlace_publi2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad')),
                ('enlace_publi3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad')),
                ('enlace_publi4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad')),
                ('enlace_publi5', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad')),
                ('genero', models.ManyToManyField(to='cursos.categorias_cursos', verbose_name='Generios Cursos:')),
                ('lenguaje', models.ManyToManyField(blank=True, null=True, to='cursos.lenguaje_cursos', verbose_name='Lenguaje Cursos:')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.plataforma_cursos', verbose_name='Indicar la Plataforma de Cursos:')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='cupones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre:')),
                ('nombre_original', models.CharField(max_length=250, verbose_name='Nombre Original:')),
                ('slug_cupon', models.SlugField(blank=True, max_length=250, null=True)),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion:')),
                ('Author', models.CharField(max_length=150)),
                ('calificacion', models.CharField(max_length=100)),
                ('descargas', models.IntegerField()),
                ('idiomas', models.CharField(blank=True, choices=[('Español Latino', 'Español Latino'), ('Español Castellano', 'Español Castellano'), ('Español Subtitulado', 'Español Subtitulado'), ('Ingles', 'Ingles')], default=('Español Latino', 'Español Latino'), max_length=150, null=True)),
                ('fecha_estreno', models.DateField(verbose_name='Fecha del Curso')),
                ('fecha_subida', models.DateField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('anio', models.CharField(blank=True, max_length=4, null=True)),
                ('trailer', models.CharField(max_length=100)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 4')),
                ('enlacegd', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive')),
                ('enlacegd2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive 2')),
                ('enlace_publi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad')),
                ('enlace_publi2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad2')),
                ('genero', models.ManyToManyField(to='cursos.categorias_cursos', verbose_name='Generios Cursos:')),
                ('lenguaje', models.ManyToManyField(blank=True, null=True, to='cursos.lenguaje_cursos', verbose_name='Lenguaje Cursos:')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.plataforma_cursos', verbose_name='Indicar la Plataforma de Cursos:')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre:')),
                ('nombre_original', models.CharField(max_length=250, verbose_name='Nombre Original:')),
                ('slug_articulo', models.SlugField(blank=True, max_length=250, null=True)),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion:')),
                ('Author', models.CharField(max_length=150)),
                ('calificacion', models.CharField(max_length=100)),
                ('descargas', models.IntegerField()),
                ('idiomas', models.CharField(blank=True, choices=[('Español Latino', 'Español Latino'), ('Español Castellano', 'Español Castellano'), ('Español Subtitulado', 'Español Subtitulado'), ('Ingles', 'Ingles')], default=('Español Latino', 'Español Latino'), max_length=150, null=True)),
                ('fecha_estreno', models.DateField(verbose_name='Fecha del Curso')),
                ('fecha_subida', models.DateField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('anio', models.CharField(blank=True, max_length=4, null=True)),
                ('trailer', models.CharField(max_length=100)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Subir Imagen 4')),
                ('enlacegd', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive')),
                ('enlacegd2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Drive 2')),
                ('enlace_publi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad')),
                ('enlace_publi2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace publicidad2')),
                ('genero', models.ManyToManyField(to='cursos.categorias_cursos', verbose_name='Generios Cursos:')),
                ('lenguaje', models.ManyToManyField(blank=True, null=True, to='cursos.lenguaje_cursos', verbose_name='Lenguaje Cursos:')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.plataforma_cursos', verbose_name='Indicar la Plataforma de Cursos:')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
