# Generated by Django 2.2.6 on 2020-05-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_descripcion_resumida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='lenguaje',
            field=models.ManyToManyField(blank=True, to='cursos.lenguaje_cursos', verbose_name='Lenguaje Cursos:'),
        ),
        migrations.AlterField(
            model_name='cupones',
            name='lenguaje',
            field=models.ManyToManyField(blank=True, to='cursos.lenguaje_cursos', verbose_name='Lenguaje Cursos:'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='lenguaje',
            field=models.ManyToManyField(blank=True, to='cursos.lenguaje_cursos', verbose_name='Lenguaje Cursos:'),
        ),
    ]
